version: "3"

services:
  database:
    image: mysql:8
    container_name: sc_database
    restart: on-failure
    env_file:
      - ../.env.local
    ports:
      - 3306:3306
    volumes:
      - dbVolume:/var/lib/mysql

  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: ../
    image: docker.pkg.github.com/iamfj/shoe-price-comparison/frontend:latest
    container_name: sc_frontend
    restart: on-failure
    depends_on:
      - database
    env_file:
      - ../.env.local
    volumes:
      - ../:/var/www/html/

  nginx:
    image: nginx:1.19.2-alpine
    container_name: sc_nginx
    restart: on-failure
    depends_on:
      - frontend
      - database
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html/
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  dbVolume:
